const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateDoctorReport = async (record, outputPath) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);
    
    // Header
    doc.fontSize(20).text('Sepsis Detection Report - Doctor Version', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Generated: ${new Date(record.createdAt).toLocaleString()}`, { align: 'center' });
    doc.moveDown(2);
    
    // Patient Information
    doc.fontSize(16).text('Patient Information', { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    doc.text(`Patient Name: ${record.patientName || 'N/A'}`);
    doc.text(`Patient Email: ${record.patientEmail || 'N/A'}`);
    doc.text(`Doctor: ${record.doctorEmail || record.doctorId || 'N/A'}`);
    doc.text(`Reported Age: ${record.patientAge || 'N/A'}`);
    doc.text(`Symptoms: ${record.symptoms || 'Not provided'}`);
    doc.moveDown();
    
    // Sepsis Detection Result
    doc.fontSize(16).text('Sepsis Detection Result', { underline: true });
    doc.moveDown();
    doc.fontSize(14);
    const sepsisStatus = record.sepsisDetected ? 'DETECTED' : 'NOT DETECTED';
    const statusColor = record.sepsisDetected ? 'red' : 'green';
    doc.fillColor(statusColor).text(`Status: ${sepsisStatus}`, { continued: false });
    doc.fillColor('black');
    doc.moveDown();
    
    // Original Model Results
    doc.fontSize(14).text('Original Model Results', { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    const orig = record.originalModelPrediction;
    doc.text(`Prediction: ${orig.prediction === 1 ? 'Sepsis' : 'No Sepsis'}`);
    doc.text(`Probability: ${(orig.probability * 100).toFixed(2)}%`);
    doc.text(`Accuracy: ${(orig.metrics.accuracy * 100).toFixed(2)}%`);
    doc.text(`Precision: ${(orig.metrics.precision * 100).toFixed(2)}%`);
    doc.text(`Recall: ${(orig.metrics.recall * 100).toFixed(2)}%`);
    doc.text(`F1 Score: ${(orig.metrics.f1_score * 100).toFixed(2)}%`);
    doc.moveDown();
    
    // VAE Model Results
    doc.fontSize(14).text('VAE-Enhanced Model Results', { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    const vae = record.vaeModelPrediction;
    doc.text(`Prediction: ${vae.prediction === 1 ? 'Sepsis' : 'No Sepsis'}`);
    doc.text(`Probability: ${(vae.probability * 100).toFixed(2)}%`);
    doc.text(`Accuracy: ${(vae.metrics.accuracy * 100).toFixed(2)}%`);
    doc.text(`Precision: ${(vae.metrics.precision * 100).toFixed(2)}%`);
    doc.text(`Recall: ${(vae.metrics.recall * 100).toFixed(2)}%`);
    doc.text(`F1 Score: ${(vae.metrics.f1_score * 100).toFixed(2)}%`);
    doc.moveDown();
    
    // Patient Data Summary
    doc.fontSize(14).text('Key Patient Metrics', { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    const data = record.patientData;
    const keyMetrics = ['HR', 'Temp', 'O2Sat', 'SBP', 'DBP', 'WBC', 'Lactate', 'Age'];
    keyMetrics.forEach(metric => {
      if (data[metric] !== undefined) {
        doc.text(`${metric}: ${data[metric]}`);
      }
    });
    doc.moveDown();
    
    // Suggestions
    doc.fontSize(14).text('Recommendations', { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    record.suggestions.forEach((suggestion, index) => {
      doc.text(`${index + 1}. ${suggestion}`);
    });
    doc.moveDown();
    
    // Footer
    doc.fontSize(10).fillColor('gray').text(
      'This report is generated by the Sepsis Detection Platform using ML models.',
      { align: 'center' }
    );
    
    doc.end();
    stream.on('finish', () => resolve(outputPath));
    stream.on('error', reject);
  });
};

const generatePatientReport = async (record, outputPath) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);
    
    // Header
    doc.fontSize(20).text('Sepsis Detection Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Generated: ${new Date(record.createdAt).toLocaleString()}`, { align: 'center' });
    doc.moveDown(2);
    
    // Sepsis Detection Result
    doc.fontSize(18).text('Test Result', { align: 'center', underline: true });
    doc.moveDown();
    doc.fontSize(16);
    const sepsisStatus = record.sepsisDetected ? 'SEPSIS DETECTED' : 'NO SEPSIS DETECTED';
    const statusColor = record.sepsisDetected ? 'red' : 'green';
    doc.fillColor(statusColor).text(sepsisStatus, { align: 'center' });
    doc.fillColor('black');
    doc.moveDown(2);
    
    // Simple Explanation
    doc.fontSize(14).text('Explanation', { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    if (record.sepsisDetected) {
      doc.text('Our analysis indicates the presence of sepsis. This is a serious condition that requires immediate medical attention.');
      doc.moveDown();
      doc.text('Please contact your healthcare provider immediately and follow their instructions.');
    } else {
      doc.text('Our analysis indicates no signs of sepsis at this time.');
      doc.moveDown();
      doc.text('However, please continue to monitor your condition and seek medical attention if symptoms worsen.');
    }
    doc.moveDown();
    
    // Recommendations
    doc.fontSize(14).text('Recommendations', { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    // Filter suggestions for patient (remove technical ones)
    const patientSuggestions = record.suggestions.filter(s => 
      !s.includes('antibiotics') || record.sepsisDetected
    );
    patientSuggestions.slice(0, 5).forEach((suggestion, index) => {
      doc.text(`${index + 1}. ${suggestion}`);
    });
    doc.moveDown();
    
    // Footer
    doc.fontSize(10).fillColor('gray').text(
      'This report is for informational purposes only. Please consult with your healthcare provider.',
      { align: 'center' }
    );
    
    doc.end();
    stream.on('finish', () => resolve(outputPath));
    stream.on('error', reject);
  });
};

module.exports = { generateDoctorReport, generatePatientReport };

